name = "ArgoData"
uuid = "9eb831cf-c491-48dc-bed4-6aca718df73c"
version = "0.2.7"
authors = ["gaelforget <gforget@mit.edu>"]

[deps]
Bootstrap = "e28b5b4c-05e8-5b66-bc03-6f0c0a0a06e0"
CSV = "336ed68f-0bac-5ca0-87d4-7b16caf5d00b"
DataDeps = "124859b0-ceae-595e-8997-d05f6a7a8dfe"
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
Dataverse = "9c0b9be8-e31e-490f-90fe-77697562404d"
Dates = "ade2ca70-3891-5945-98fb-dc099432e06a"
Downloads = "f43a241f-c20a-4ad4-852c-f6b1247861c6"
FTPClient = "01fcc997-4f28-56b8-8a06-30002c134abb"
Glob = "c27321d9-0574-5035-807b-f59d2c89b15c"
Interpolations = "a98d9a8b-a2ab-59e6-89dd-64a1c18fca59"
IntervalSets = "8197267c-284f-5f27-9208-e0e47529a953"
JLD2 = "033835bb-8acc-5ee8-8aae-3f567f8a3819"
MeshArrays = "cb8c808f-1acf-59a3-9d2b-6e38d009f683"
NCDatasets = "85f8d34a-cbdd-5861-8df4-14fed0d494ab"
NetworkOptions = "ca575930-c2e3-43a9-ace4-1e988b2c1908"
OrderedCollections = "bac558e1-5e72-5ebc-8fee-abe8a469f55d"
Parquet2 = "98572fba-bba0-415d-956f-fa77e587d26d"
Pkg = "44cfe95a-1eb2-52ea-b672-e2afdf69b78f"
Printf = "de0858da-6303-5e67-8744-51eddeeeb8d7"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"
TableOperations = "ab02a1b2-a7df-11e8-156e-fb1833f50b87"
Tables = "bd369af6-aec1-5ad0-b16a-f7cc5008161c"
YAML = "ddb6d928-2868-570f-bddf-ab3f9cf99eb6"

[weakdeps]
Climatology = "9e9a4d37-2d2e-41e3-8b85-f7978328d9c7"
Conda = "8f4d0f93-b110-5947-807f-2305c1781a2d"
CondaPkg = "992eb4ea-22a4-4c89-a5bb-47a3300528ab"
Makie = "ee78f7c6-11fb-53f2-987a-cfe4a2b5a57a"
PyCall = "438e738f-606a-5dbb-bf0a-cddfbfd45ab0"
PythonCall = "6099a3de-0909-46bc-b1f4-468b9a2dfc0d"

[extensions]
ArgoDataClimatologyExt = ["Climatology"]
ArgoDataCondaExt = ["Conda"]
ArgoDataCondaPkgExt = ["CondaPkg"]
ArgoDataMakieExt = ["Makie"]
ArgoDataPyCallExt = ["PyCall"]
ArgoDataPythonCallExt = ["PythonCall"]

[compat]
Bootstrap = "2"
CSV = "0.10"
Climatology = "0.5"
Conda = "1"
CondaPkg = "0.2"
DataDeps = "0.7"
DataFrames = "1"
Dataverse = "0.2"
Downloads = "1"
FTPClient = "1"
Glob = "1"
Interpolations = "0.13, 0.14, 0.15, 0.16"
IntervalSets = "0.7"
JLD2 = "0.4, 0.5, 0.6"
Makie = "0.21, 0.22, 0.23, 0.24"
MeshArrays = "0.3, 0.4, 0.5"
NCDatasets = "0.12, 0.13, 0.14"
NetworkOptions = "1"
OrderedCollections = "1"
Parquet2 = "0.2"
PyCall = "1"
PythonCall = "0.9"
Statistics = "1"
TableOperations = "1"
Tables = "1"
YAML = "0.4"
julia = "1.9"
